name: Build
permissions:
  contents: read

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  alpine:
    runs-on: ubuntu-latest
    container: alpine:latest

    steps:
      - name: Install Dependencies
        run: apk add gcc make libc-dev

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: make

      - name: Run Example
        run: ./example


  debian:
    runs-on: ubuntu-latest
    container: debian:latest

    steps:
      - name: Install Dependencies
        run: |
          apt update
          apt install -y make gcc

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: make

      - name: Run Example
        run: ./example


  void-glibc:
    runs-on: ubuntu-latest
    container: ghcr.io/void-linux/void-glibc:latest
    steps:
      - name: Install dependencies
        run: xbps-install -Sy git make gcc

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: make

      - name: Run Example
        run: ./example
