name: C Build

on: [push, pull_request]

jobs:
  alpine:
    runs-on: ubuntu-latest
    container: alpine:latest

    steps:
      - name: Install Dependencies
        run: apk add gcc make

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: make


  debian:
    runs-on: ubuntu-latest
    container: debian:latest

    steps:
      - name: Install Dependencies
        run: |
          apt update
          apt install -y build-essential

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: make


  void-glibc:
    runs-on: ubuntu-latest
    container: ghcr.io/void-linux/void-glibc:latest
    steps:
      - name: Install dependencies
        run: xbps-install -Sy git base-devel

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: make
