name: C Build

on: [push, pull_request]

jobs:
  debian:
    runs-on: ubuntu-latest
    container: debian:latest

    steps:
      - name: Install Dependencies
        run: |
          apt update
          apt install -y build-essential

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: make


  void-linux:
    runs-on: ubuntu-latest
    container: voidlinux/voidlinux-glibc:latest
    steps:
      - name: Install dependencies
        run: xbps-install -Sy base-devel

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: make
