name: C Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: make
