name: C
permissions:
  contents: read

on:
  push:
    branches:
      - "master"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.os }} / ${{ matrix.cc }}
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    strategy:
      matrix:
        include:
          - os: alpine
            cc: gcc
            image: alpine:latest
            install: apk add libc-dev gcc

          - os: alpine
            cc: clang
            image: alpine:latest
            install: apk add libc-dev clang

          - os: debian
            cc: gcc
            image: debian:latest
            install: apt update && apt install -y gcc

          - os: debian
            cc: clang
            image: debian:latest
            install: apt update && apt install -y clang

    env:
      CC: ${{ matrix.cc }}

    steps:
      - name: Install Dependencies
        run: ${{ matrix.install }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Bootstrap nob
        run: $CC -Werror -o nob nob.c

      - name: Build
        run: ./nob

      - name: Run Example
        run: ./example
